export type RegionOption = {
    code: string;
    isoCode: string;
    label: string;
    name: string;
};

const NUMERIC_REGION_DATA: ReadonlyArray<{ code: string; label: string }> = [
    { code: '01', label: 'Республика Адыгея (Адыгея)' },
    { code: '02', label: 'Республика Башкортостан' },
    { code: '03', label: 'Республика Бурятия' },
    { code: '04', label: 'Республика Алтай' },
    { code: '05', label: 'Республика Дагестан' },
    { code: '06', label: 'Республика Ингушетия' },
    { code: '07', label: 'Кабардино-Балкарская Республика' },
    { code: '08', label: 'Республика Калмыкия' },
    { code: '09', label: 'Карачаево-Черкесская Республика' },
    { code: '10', label: 'Республика Карелия' },
    { code: '11', label: 'Республика Коми' },
    { code: '12', label: 'Республика Марий Эл' },
    { code: '13', label: 'Республика Мордовия' },
    { code: '14', label: 'Республика Саха (Якутия)' },
    { code: '15', label: 'Республика Северная Осетия - Алания' },
    { code: '16', label: 'Республика Татарстан (Татарстан)' },
    { code: '17', label: 'Республика Тыва' },
    { code: '18', label: 'Удмуртская Республика' },
    { code: '19', label: 'Республика Хакасия' },
    { code: '20', label: 'Чеченская Республика' },
    { code: '21', label: 'Чувашская Республика - Чувашия' },
    { code: '22', label: 'Алтайский край' },
    { code: '23', label: 'Краснодарский край' },
    { code: '24', label: 'Красноярский край' },
    { code: '25', label: 'Приморский край' },
    { code: '26', label: 'Ставропольский край' },
    { code: '27', label: 'Хабаровский край' },
    { code: '28', label: 'Амурская область' },
    { code: '29', label: 'Архангельская область' },
    { code: '30', label: 'Астраханская область' },
    { code: '31', label: 'Белгородская область' },
    { code: '32', label: 'Брянская область' },
    { code: '33', label: 'Владимирская область' },
    { code: '34', label: 'Волгоградская область' },
    { code: '35', label: 'Вологодская область' },
    { code: '36', label: 'Воронежская область' },
    { code: '37', label: 'Ивановская область' },
    { code: '38', label: 'Иркутская область' },
    { code: '39', label: 'Калининградская область' },
    { code: '40', label: 'Калужская область' },
    { code: '41', label: 'Камчатский край' },
    { code: '42', label: 'Кемеровская область' },
    { code: '43', label: 'Кировская область' },
    { code: '44', label: 'Костромская область' },
    { code: '45', label: 'Курганская область' },
    { code: '46', label: 'Курская область' },
    { code: '47', label: 'Ленинградская область' },
    { code: '48', label: 'Липецкая область' },
    { code: '49', label: 'Магаданская область' },
    { code: '50', label: 'Московская область' },
    { code: '51', label: 'Мурманская область' },
    { code: '52', label: 'Нижегородская область' },
    { code: '53', label: 'Новгородская область' },
    { code: '54', label: 'Новосибирская область' },
    { code: '55', label: 'Омская область' },
    { code: '56', label: 'Оренбургская область' },
    { code: '57', label: 'Орловская область' },
    { code: '58', label: 'Пензенская область' },
    { code: '59', label: 'Пермский край' },
    { code: '60', label: 'Псковская область' },
    { code: '61', label: 'Ростовская область' },
    { code: '62', label: 'Рязанская область' },
    { code: '63', label: 'Самарская область' },
    { code: '64', label: 'Саратовская область' },
    { code: '65', label: 'Сахалинская область' },
    { code: '66', label: 'Свердловская область' },
    { code: '67', label: 'Смоленская область' },
    { code: '68', label: 'Тамбовская область' },
    { code: '69', label: 'Тверская область' },
    { code: '70', label: 'Томская область' },
    { code: '71', label: 'Тульская область' },
    { code: '72', label: 'Тюменская область' },
    { code: '73', label: 'Ульяновская область' },
    { code: '74', label: 'Челябинская область' },
    { code: '75', label: 'Забайкальский край' },
    { code: '76', label: 'Ярославская область' },
    { code: '77', label: 'г. Москва' },
    { code: '78', label: 'Санкт-Петербург' },
    { code: '79', label: 'Еврейская автономная область' },
    { code: '83', label: 'Ненецкий автономный округ' },
    { code: '86', label: 'Ханты-Мансийский автономный округ - Югра' },
    { code: '87', label: 'Чукотский автономный округ' },
    { code: '89', label: 'Ямало-Ненецкий автономный округ' },
    { code: '99', label: 'Иные территории, включая город и космодром Байконур' },
] as const;

const ISO_REGION_DATA: ReadonlyArray<{ isoCode: string; label: string }> = [
    { isoCode: 'RU-AD', label: 'Республика Адыгея (Адыгея)' },
    { isoCode: 'RU-BA', label: 'Республика Башкортостан' },
    { isoCode: 'RU-BU', label: 'Республика Бурятия' },
    { isoCode: 'RU-AL', label: 'Республика Алтай' },
    { isoCode: 'RU-DA', label: 'Республика Дагестан' },
    { isoCode: 'RU-IN', label: 'Республика Ингушетия' },
    { isoCode: 'RU-KB', label: 'Кабардино-Балкарская Республика' },
    { isoCode: 'RU-KL', label: 'Республика Калмыкия' },
    { isoCode: 'RU-KC', label: 'Карачаево-Черкесская Республика' },
    { isoCode: 'RU-KR', label: 'Республика Карелия' },
    { isoCode: 'RU-KO', label: 'Республика Коми' },
    { isoCode: 'RU-ME', label: 'Республика Марий Эл' },
    { isoCode: 'RU-MO', label: 'Республика Мордовия' },
    { isoCode: 'RU-SA', label: 'Республика Саха (Якутия)' },
    { isoCode: 'RU-SE', label: 'Республика Северная Осетия - Алания' },
    { isoCode: 'RU-TA', label: 'Республика Татарстан (Татарстан)' },
    { isoCode: 'RU-TY', label: 'Республика Тыва' },
    { isoCode: 'RU-UD', label: 'Удмуртская Республика' },
    { isoCode: 'RU-KK', label: 'Республика Хакасия' },
    { isoCode: 'RU-CE', label: 'Чеченская Республика' },
    { isoCode: 'RU-CU', label: 'Чувашская Республика - Чувашия' },
    { isoCode: 'RU-ALT', label: 'Алтайский край' },
    { isoCode: 'RU-KDA', label: 'Краснодарский край' },
    { isoCode: 'RU-KYA', label: 'Красноярский край' },
    { isoCode: 'RU-PRI', label: 'Приморский край' },
    { isoCode: 'RU-STA', label: 'Ставропольский край' },
    { isoCode: 'RU-KHA', label: 'Хабаровский край' },
    { isoCode: 'RU-AMU', label: 'Амурская область' },
    { isoCode: 'RU-ARK', label: 'Архангельская область' },
    { isoCode: 'RU-AST', label: 'Астраханская область' },
    { isoCode: 'RU-BEL', label: 'Белгородская область' },
    { isoCode: 'RU-BRY', label: 'Брянская область' },
    { isoCode: 'RU-VLA', label: 'Владимирская область' },
    { isoCode: 'RU-VGG', label: 'Волгоградская область' },
    { isoCode: 'RU-VLG', label: 'Вологодская область' },
    { isoCode: 'RU-VOR', label: 'Воронежская область' },
    { isoCode: 'RU-IVA', label: 'Ивановская область' },
    { isoCode: 'RU-IRK', label: 'Иркутская область' },
    { isoCode: 'RU-KGD', label: 'Калининградская область' },
    { isoCode: 'RU-KLU', label: 'Калужская область' },
    { isoCode: 'RU-KAM', label: 'Камчатский край' },
    { isoCode: 'RU-KEM', label: 'Кемеровская область' },
    { isoCode: 'RU-KIR', label: 'Кировская область' },
    { isoCode: 'RU-KOS', label: 'Костромская область' },
    { isoCode: 'RU-KGN', label: 'Курганская область' },
    { isoCode: 'RU-KRS', label: 'Курская область' },
    { isoCode: 'RU-LEN', label: 'Ленинградская область' },
    { isoCode: 'RU-LIP', label: 'Липецкая область' },
    { isoCode: 'RU-MAG', label: 'Магаданская область' },
    { isoCode: 'RU-MOS', label: 'Московская область' },
    { isoCode: 'RU-MUR', label: 'Мурманская область' },
    { isoCode: 'RU-NIZ', label: 'Нижегородская область' },
    { isoCode: 'RU-NGR', label: 'Новгородская область' },
    { isoCode: 'RU-NVS', label: 'Новосибирская область' },
    { isoCode: 'RU-OMS', label: 'Омская область' },
    { isoCode: 'RU-ORE', label: 'Оренбургская область' },
    { isoCode: 'RU-ORL', label: 'Орловская область' },
    { isoCode: 'RU-PNZ', label: 'Пензенская область' },
    { isoCode: 'RU-PER', label: 'Пермский край' },
    { isoCode: 'RU-PSK', label: 'Псковская область' },
    { isoCode: 'RU-ROS', label: 'Ростовская область' },
    { isoCode: 'RU-RYA', label: 'Рязанская область' },
    { isoCode: 'RU-SAM', label: 'Самарская область' },
    { isoCode: 'RU-SAR', label: 'Саратовская область' },
    { isoCode: 'RU-SAK', label: 'Сахалинская область' },
    { isoCode: 'RU-SVE', label: 'Свердловская область' },
    { isoCode: 'RU-SMO', label: 'Смоленская область' },
    { isoCode: 'RU-TAM', label: 'Тамбовская область' },
    { isoCode: 'RU-TVE', label: 'Тверская область' },
    { isoCode: 'RU-TOM', label: 'Томская область' },
    { isoCode: 'RU-TUL', label: 'Тульская область' },
    { isoCode: 'RU-TYU', label: 'Тюменская область' },
    { isoCode: 'RU-ULY', label: 'Ульяновская область' },
    { isoCode: 'RU-CHE', label: 'Челябинская область' },
    { isoCode: 'RU-ZAB', label: 'Забайкальский край' },
    { isoCode: 'RU-YAR', label: 'Ярославская область' },
    { isoCode: 'RU-MOW', label: 'г. Москва' },
    { isoCode: 'RU-SPE', label: 'Санкт-Петербург' },
    { isoCode: 'RU-YEV', label: 'Еврейская автономная область' },
    { isoCode: 'RU-NEN', label: 'Ненецкий автономный округ' },
    { isoCode: 'RU-KHM', label: 'Ханты-Мансийский автономный округ - Югра' },
    { isoCode: 'RU-CHU', label: 'Чукотский автономный округ' },
    { isoCode: 'RU-YAN', label: 'Ямало-Ненецкий автономный округ' },
    { isoCode: 'RU-OTHER', label: 'Иные территории, включая город и космодром Байконур' },
] as const;

const labelToNumeric = new Map(NUMERIC_REGION_DATA.map((item) => [item.label, item.code]));

export const REGIONS: readonly RegionOption[] = ISO_REGION_DATA.map((region) => {
    const numericCode = labelToNumeric.get(region.label);
    return {
        code: numericCode ?? region.isoCode,
        isoCode: region.isoCode,
        label: region.label,
        name: region.label,
    };
});

export const REGION_MAP = new Map(REGIONS.map((region) => [region.code, region]));
export const REGION_ISO_MAP = new Map(REGIONS.map((region) => [region.isoCode, region]));
