version: '3.8'
services:
  app:
    build: .
    container_name: ci-work_app
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: 'mongodb://admin:secret123@mongo:27017/ci_work?authSource=admin'
      S3_ENDPOINT: 'https://s3.regru.cloud'
      S3_ACCESS_KEY_ID: '6SGVNS8EGMF6EY3QPIRS'
      S3_SECRET_ACCESS_KEY: 'DjfoXfJsdYQvfiwAi01YBWhsPa8jtEuBZXq7CyWZ'
      S3_BUCKET_NAME: 'ci-work'
      S3_REGION: 'us-east-1'
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    command:
      ['mongod', '--setParameter', 'diagnosticDataCollectionEnabled=false']
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ci-work_db_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  ci-work_db_data:
    name: ci-work_db_data

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: '1450'
