services:
  app:
    build: .
    container_name: ci-work_app
    env_file: .env.production
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    command:
      ['mongod', '--setParameter', 'diagnosticDataCollectionEnabled=false']
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ci-work_db_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  ci-work_db_data:
    name: ci-work_db_data

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: '1450'
