version: '3.8'

services:
  app:
    build: .
    container_name: ci-work_app
    ports:
      - '3000:3000'
    environment:
      # Замените URL подключения к MongoDB, если надо
      MONGODB_URI: 'mongodb://mongo:27017/your_database'
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    volumes:
      - db_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  db_data:
