version: '3.8'

services:
  # Сервис приложения
  app:
    build: .
    container_name: ci-work-app
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      #
      #
    depends_on:
      - mongo
    restart: unless-stopped

  # Сервис MongoDB
  mongo:
    image: mongo:6
    container_name: ci-work-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db
